### ISSUE TITLE
Issue in Plotting

### ISSUE THREAD

**Issue by nifanilo** [dportik/dadi_pipeline#23]
Hi all, 

I have a problem with plotting. 
When I ran the Make_Plots.py, I got this error: 

Fitting model 'sym_mig' to empirical data...
============================================================================

Input parameters = [9.5185, 1.9965, 0.7604, 0.5057]

                        Likelihood = -171,473.62
                        AIC = 342,955.24
                        Theta = 94,929.83
                        Chi-Squared = 1,388,182.89

============================================================================
Creating plots
============================================================================

Plotting pop0_pop1_sym_mig.pdf

NOTE - CLOSE PLOT TO ADVANCE.
Traceback (most recent call last):
  File "Make_Plots_niloo.py", line 171, in <module>
    Plotting_Functions.Plot_2D(fs, model_fit, prefix, "sym_mig")
  File "/gpfs1/data/oenanthe/niloo_oenanthe/work_10-05-2024/bunting/dadi/dadi_pipeline/Plotting/Plotting_Functions.py", line 112, in Plot_2D
    dadi.Plotting.plot_2d_comp_multinom(model_fit, fs, resid_range = 3)
  File "/home/alaeikak/anaconda3/lib/python3.7/site-packages/dadi/Plotting.py", line 308, in plot_2d_comp_multinom
    adjust=adjust,show=show)
  File "/home/alaeikak/anaconda3/lib/python3.7/site-packages/dadi/Plotting.py", line 469, in plot_2d_comp_Poisson
    pop_ids=data_pop_ids, colorbar=False)
  File "/home/alaeikak/anaconda3/lib/python3.7/site-packages/dadi/Plotting.py", line 180, in plot_single_2d_sfs
    cb = ax.figure.colorbar(mappable, extend=extend, format=format)
  File "/home/alaeikak/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 2215, in colorbar
    cb = cbar.colorbar_factory(cax, mappable, **cb_kw)
  File "/home/alaeikak/anaconda3/lib/python3.7/site-packages/matplotlib/colorbar.py", line 1640, in colorbar_factory
    cb = Colorbar(cax, mappable, **kwargs)
  File "/home/alaeikak/anaconda3/lib/python3.7/site-packages/matplotlib/colorbar.py", line 1183, in __init__
    ColorbarBase.__init__(self, ax, **kw)
  File "/home/alaeikak/anaconda3/lib/python3.7/site-packages/matplotlib/colorbar.py", line 460, in __init__
    self.draw_all()
  File "/home/alaeikak/anaconda3/lib/python3.7/site-packages/matplotlib/colorbar.py", line 483, in draw_all
    self._process_values()
  File "/home/alaeikak/anaconda3/lib/python3.7/site-packages/matplotlib/colorbar.py", line 932, in _process_values
    b = self.norm.inverse(self._uniform_y(self.cmap.N + 1))
  File "/home/alaeikak/anaconda3/lib/python3.7/site-packages/matplotlib/colors.py", line 1127, in inverse
    return vmin * np.ma.power((vmax / vmin), val)
ZeroDivisionError: float division by zero

Do you have any idea why I got this error? and how I can solve it.

The best and thanks for your help
Niloo

**Comment by dportik** [comment]
Hi @nifanilo ,
This is a known issue and is described with the solution here:

https://github.com/dportik/dadi_pipeline/tree/master/Plotting#helpful-tips
